# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Memorize' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memorize
  pod 'Alamofire', '~> 5.8'
  pod 'SQLite.swift', '~> 0.15.0'

end

